
% of loan customers unable to repay their loans

KPI 1 — Loan Default Rate

Loan Default Rate % = 
DIVIDE(
    COUNTROWS(FILTER(public fintech, public fintech[loan_repayment_status] = "Defaulted")),
    COUNTROWS(FILTER(public fintech, public fintech[has_loan] = "Yes")),
    0
) * 100



Customers whose loan amount exceeds their savings

KPI 2 — High Risk Exposure (DSR > 1.0)

High Risk Exposure % = 
DIVIDE(
    COUNTROWS(FILTER(public fintech, 
        public fintech[has_loan] = "Yes" && 
        public fintech[outstanding_loan_balance] / public fintech[savings_balance] > 1)),
    COUNTROWS(FILTER(public fintech, public fintech[has_loan] = "Yes")),
    0
) * 100






Customers holding both fixed deposits and insurance

KPI 3 — Cross-Sell Penetration

Cross Sell Penetration % = 
DIVIDE(
    COUNTROWS(
        FILTER(
            'public fintech',
            'public fintech'[account_status] = "Active" &&
            'public fintech'[has_fixed_deposit] = "Yes" &&
            'public fintech'[has_insurance] = "Yes" ) ),
 COUNTROWS(
        FILTER(
            'public fintech',
            'public fintech'[account_status] = "Active"  ) ), 0)  



Active customers using the mobile banking app

KPI 4 — Mobile App Adoption

App Adoption Rate % = 
DIVIDE(
    COUNTROWS(FILTER(public fintech, 
        public fintech[mobile_app_user] = "Yes" && 
        public fintech[account_status] = "Active")),
    COUNTROWS(FILTER(public fintech, public fintech[account_status] = "Active")),
    0
) * 100



Average savings held by active customers

KPI 5 — Average Savings per Customer

Avg Savings Per Customer = 
AVERAGEX(
    FILTER(public fintech, 
        public fintech[account_status] = "Active" && 
        NOT ISBLANK(public fintech[savings_balance])),
    public fintech[savings_balance]
)